apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myservicea
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: myservicea.foo.org
      http:
        paths:
          - path: /
            backend:
              serviceName: myservicea
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myserviceb
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: myserviceb.foo.org
      http:
        paths:
          - path: /
            backend:
              serviceName: myserviceb
              servicePort: 80
